<div class="row">
	<div class="col-sm-12">
		<h3>New Paper</h3>
		<form method="post" name="addPaper" action="add-paper.php">
			<label>Title</label>
			<input class="input-bar" type="text" name="newPaperTitle"/>
			<label>Abstract</label>
			<textarea class="input-bar" rows="8" name="newPaperAbstract"></textarea>
			<label>Citation</label>
			<input class="input-bar" type="text" name="newPaperCitation"/>
			<label>Keywords</label>
			<input class="input-bar" type="text" name="newPaperKeyword"/>
			<input class="btn comment-btn" type="submit" value="Save Changes" name="addNewPaper"/>
		</form>
	</div>
</div>