<nav>
	<div class="container">
	<div class="row">
		<div class="col-sm-8">
			<h1><a href="index.php">Faculty Research Database</a></h1>
		</div>
		<div class="col-sm-4 login-container">
			<div class="row">
				<div class="col-xs-9">
					<h4><a href="profile.php" class="profile-name">Tom Babasidis</a></h4>
					Not You? <a href="index.php">Sign out.</a>
				</div>
				<div class="col-xs-3">
					<img src="img/avatar.jpg" class="img-circle" alt="Avatar" width="50" height="50"> 
				</div>
			</div>
		</div>
	</div>
	</div>
</nav>