	<div class="row">
		<div class="col-sm-8">
			<h2>Featured Papers</h2>
			<div class="row">
			<form action="index.php" method="post" name="SearchForm">
				<div class="col-sm-5">
					<input name="searchPhrase" type="text" class="paper-search-bar" placeholder="search papers"/>
				</div>
				<div class="col-sm-1 in">
					in
				</div>
				<div class="col-sm-4">
					<select class="paper-search-select" name="searchField">
						<option value="allFields">-- All Fields --</option>
						<option value="title">Title</option>
						<option value="citation">Citation</option>
						<option value="abstract">Abstract</option>
					</select>
				</div>
				<div class="col-sm-2">

				<input type="submit" name="searched" class="btn comment-btn" value="Search"/>
			</form>
				</div>
			</div>


			
		
