<div class="row">
	<div class="col-sm-12">
		<h3>Comments</h3>
		<p><strong>Tom: </strong> January 3, 2015 11:43 AM</p>
		<p>
			Mauris consequat risus sed dui maximus, id bibendum ex convallis. Vivamus pellentesque diam a volutpat dapibus. Vivamus sodales purus mauris. Integer nec viverra purus. Nullam et orci id mi egestas gravida vitae quis ligula.
		</p>

		<br/>
		<h5>Add a Comment</h5>
		<textarea class="paper-comment-area" placeholder="Add your comment"></textarea>
		<button class="btn comment-btn">Add Comment</button>
	</div>
</div>